import type { Metadata } from "next";
import { Inter, Titillium_Web } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import BeforeFooter from "@/components/Footer/BeforeFooter";
import Navbar from "@/components/Navbar/Navbar";

const inter = Titillium_Web({
  subsets: ["latin"],
  style: "normal",
  weight: ["200", "300", "400", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <BeforeFooter />
        <Footer />
      </body>
    </html>
  );
}
